Repository simple-robot/simbot-component-mirai, pull requests merged in 2022-08, with the labels that each got.

#59 修复群成员无法解除禁言的问题
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
Labels: bug

#61 为MiraiMember提供 `nickname`、`specialTitle`、`joinTime`、`lastSpeakTime` 的更多属性支持
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
Labels: 优化

#62 为「转发消息」提供simbot层面的封装
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiComponent.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiReceivedMessageContent.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiAudio.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiForwardMessage.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiImage.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiMessageChainContainer.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiMessageChainContent.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiMessageParser.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiNudge.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiQuoteReply.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiSimbotMessages.kt
Labels: 特性

#65 实现新的密码配置形式
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManager.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
  simbot-component-mirai-core/src/test/kotlin/DeviceInfoTest.kt
Labels: 特性

#66 为MiraiGroup实现DeleteSupport
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiGroup.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiGroupImpl.kt
Labels: 特性

#67 优化MiraiGroup中的mute相关api
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiGroup.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiGroupImpl.kt
Labels: 优化

#68 新的设备信息配置形式
  simbot-component-mirai-core/bot.config.json
  simbot-component-mirai-core/build.gradle.kts
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManager.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
  simbot-component-mirai-core/src/test/kotlin/DeviceInfoTest.kt
  simbot-component-mirai-core/src/test/kotlin/SerTest.kt
  simbot-component-mirai-core/src/test/resources/test.json
  simbot-component-mirai-core/src/test/resources/test.yaml
Labels: 特性

#69 调整、优化MiraiBotVerifyInfoConfiguration配置相关内容
  buildSrc/src/main/kotlin/simbot-mirai.module-conventions.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/DeviceInfoConfiguration.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManager.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/PasswordInfoConfiguration.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotManagerImpl.kt
  simbot-component-mirai-core/src/test/kotlin/BotVerifyInfoConfigurationTest.kt
  simbot-component-mirai-core/src/test/kotlin/SerTest.kt
Labels: 优化

#70 更新 `mirai-core` 版本到 v2.12.1
  libs.versions.toml
  simbot-component-mirai-core/bot.config.json
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiGroupSettingEvents.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiGroupSettingEventImpls.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiMessageParser.kt
Labels: 特性

#72 配置项 `deviceInfo` 支持类型 `file_based`
  buildSrc/src/main/kotlin/P.kt
  simbot-component-mirai-core/bot.config.json
  simbot-component-mirai-core/build.gradle.kts
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/SimpleDeviceInfo.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/DeviceInfoConfiguration.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
Labels: 特性

#73 为 `MiraiMember` 提供更多禁言和匿名相关的属性
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
Labels: 特性

#74 为 `MiraiMember` 提供管理员任免相关API
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
Labels: 特性

#75 为「缓存策略」提供新的配置形式 `recallMessageCacheStrategyConfig`
  buildSrc/src/main/kotlin/P.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiRecallMessageCacheStrategy.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/StandardMiraiRecallMessageCacheStrategyImpl.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
  simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/RecallMessageCacheStrategyConfiguration.kt
  simbot-component-mirai-core/src/test/kotlin/BotVerifyInfoConfigurationTest.kt
Labels: 特性
